module.exports = [
  { name: 'turquoise', color: '#1abc9c' },
  { name: 'green_sea', color: '#16a085' },
  { name: 'emerald', color: '#2ecc71' },
  { name: 'nephritis', color: '#27ae60' },
  { name: 'peter_river', color: '#3498db' },
  { name: 'belize_hole', color: '#2980b9' },
  { name: 'amethyst', color: '#9b59b6' },
  { name: 'wisteria', color: '#8e44ad' },
  { name: 'wet_asphalt', color: '#34495e' },
  { name: 'midnight_blue', color: '#2c3e50' },
  { name: 'sunflower', color: '#f1c40f' },
  { name: 'orange', color: '#f39c12' },
  { name: 'carrot', color: '#e67e22' },
  { name: 'pumpkin', color: '#d35400' },
  { name: 'alizarin', color: '#e74c3c' },
  { name: 'pomegranate', color: '#c0392b' },
  { name: 'clouds', color: '#ecf0f1' },
  { name: 'silver', color: '#bdc3c7' },
  { name: 'concrete', color: '#95a5a6' },
  { name: 'asbestos', color: '#7f8c8d' },
];
