module.exports = [
  { name: 'turquoise', light: '#E8F8F5', dark: '#0E6251' },
  { name: 'green_sea', light: '#E8F6F3', dark: '#0B5345' },
  { name: 'emerald', light: '#EAFAF1', dark: '#186A3B' },
  { name: 'nephritis', light: '#E9F7EF', dark: '#145A32', alias: 'green' },
  { name: 'peter_river', light: '#EBF5FB', dark: '#1B4F72', alias: 'blue' },
  { name: 'belize_hole', light: '#EAF2F8', dark: '#154360' },
  { name: 'amethyst', light: '#F5EEF8', dark: '#512E5F' },
  { name: 'wisteria', light: '#F4ECF7', dark: '#4A235A', alias: 'purple' },
  { name: 'wet_asphalt', light: '#EBEDEF', dark: '#1B2631', alias: 'grey' },
  { name: 'midnight_blue', light: '#EAECEE', dark: '#17202A' },
  { name: 'sunflower', light: '#FEF9E7', dark: '#7D6608', alias: 'yellow' },
  { name: 'orange', light: '#FEF5E7', dark: '#7E5109' },
  { name: 'carrot', light: '#FDF2E9', dark: '#784212' },
  { name: 'pumpkin', light: '#FBEEE6', dark: '#6E2C00' },
  { name: 'alizarin', light: '#FDEDEC', dark: '#78281F' },
  { name: 'pomegranate', light: '#F9EBEA', dark: '#641E16', alias: 'red' },
  { name: 'clouds', light: '#FDFEFE', dark: '#7B7D7D' },
  { name: 'silver', light: '#F8F9F9', dark: '#626567' },
  { name: 'concrete', light: '#F4F6F6', dark: '#4D5656' },
  { name: 'asbestos', light: '#F2F4F4', dark: '#424949' },
];
